#!/usr/bin/env ruby

commit_comment = case ARGV.length
                   when 1
                     ARGV[0]
                   when 2
                     "#{ARGV[1]} --IS-#{ARGV[0]}"
                   else
                     nil
                 end

current_branch = `git rev-parse --abbrev-ref HEAD`.chomp
current_dir = `pwd`.split('/').last.chomp
system(%(git commit -m '#{current_dir}(#{current_branch}): #{commit_comment}'))
