#!/usr/bin/env ruby

current_branch = `git rev-parse --abbrev-ref HEAD`.chomp
system('git checkout master')
system('git pull origin master')
system("git checkout #{current_branch}")
pr_url = `push && hub pull-request --no-edit`
`open #{pr_url}`
