#!/usr/bin/env ruby

dir = ENV["WORK_DIR"] || '.'
system(%(grep -Rrn --include="*.js" --include="*.rb" --include="*.yml" --include="*.erb" --include="*.jbuilder" --include="*.axlsx" --color "#{ARGV[0]}" #{dir}))
