#!/usr/bin/env ruby

current_branch = `git rev-parse --abbrev-ref HEAD`
system('git checkout master')
system('git pull origin master')
system("git checkout #{current_branch}")
system('git rebase master')
system("git push origin #{current_branch} -f")
